export const creatorData = [
  {
    id: 1,
    name: 'Emma Wilson',
    category: 'Web Designer',
    description: 'Specialized in responsive websites and modern user experiences. 5+ years of professional experience.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop',
    rating: 4.9,
    projects: 127,
  },
  {
    id: 2,
    name: 'Michael Scott',
    category: 'UI/UX Designer',
    description: 'Creating beautiful interfaces with attention to detail. Expert in design systems and prototyping.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    rating: 4.8,
    projects: 98,
  },
  {
    id: 3,
    name: 'Olivia Brown',
    category: 'Graphic Designer',
    description: 'Visual storytelling through compelling graphics and brand identity design.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop',
    rating: 4.7,
    projects: 156,
  },
  {
    id: 4,
    name: 'David Chen',
    category: 'Content Creator',
    description: 'Creating engaging content across multiple platforms. Expertise in video and written content.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
    rating: 4.9,
    projects: 203,
  },
  {
    id: 5,
    name: 'Sarah Martinez',
    category: 'Video Editor',
    description: 'Professional video editing with motion graphics. Specializing in cinematic storytelling.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=500&fit=crop',
    rating: 4.8,
    projects: 89,
  },
  {
    id: 6,
    name: 'James Anderson',
    category: 'Motion Designer',
    description: 'Creating stunning animations and visual effects. Expert in After Effects and Cinema 4D.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    rating: 4.9,
    projects: 142,
  },
  {
    id: 7,
    name: 'Jessica Taylor',
    category: 'Digital Marketer',
    description: 'Strategic digital marketing and brand growth. Data-driven approach to campaign optimization.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop',
    rating: 4.7,
    projects: 174,
  },
];
